import { apiUrl } from '@/shared/api/config'
import type { ApiModule } from '@/shared/api/types'

export default {
    name: 'SUPERADMIN_API',
    api: {
        colleges: {
            list:apiUrl('/superadmin/colleges'),
            byId: (id: string | number) => apiUrl(`/superadmin/colleges/${id}`),
            createWithAdmin: apiUrl('/superadmin/colleges/create.with.admin'),
            update: (id: string | number) => apiUrl(`/superadmin/colleges/${id}`),
            delete: (id: string | number) => apiUrl(`/superadmin/colleges/${id}`),
        },
        modalityTypes: {
            list: apiUrl('/superadmin/modality-types'),
            byId: (id: string | number) => apiUrl(`/superadmin/modality-types/${id}`),
            create: apiUrl('/superadmin/modality-types'),
            defaultConfig: apiUrl('/superadmin/modality-types/config/default'),
            update: (id: string | number) => apiUrl(`/superadmin/modality-types/${id}`),
            delete: (id: string | number) => apiUrl(`/superadmin/modality-types/${id}`),
        },
        careers: {
            list: apiUrl('/superadmin/careers'),
            byId: (id: string | number) => apiUrl(`/superadmin/careers/${id}`),
            create: apiUrl('/superadmin/careers'),
            update: (id: string | number) => apiUrl(`/superadmin/careers/${id}`),
            delete: (id: string | number) => apiUrl(`/superadmin/careers/${id}`),
            approve: (id: string | number) => apiUrl(`/superadmin/careers/${id}/approve`),
            reject: (id: string | number) => apiUrl(`/superadmin/careers/${id}/reject`),
        },
        subjects: {
            list: apiUrl('/superadmin/subjects'),
            byId: (id: string | number) => apiUrl(`/superadmin/subjects/${id}`),
            create: apiUrl('/superadmin/subjects'),
            update: (id: string | number) => apiUrl(`/superadmin/subjects/${id}`),
            delete: (id: string | number) => apiUrl(`/superadmin/subjects/${id}`),
            approve: (id: string | number) => apiUrl(`/superadmin/subjects/${id}/approve`),
            reject: (id: string | number) => apiUrl(`/superadmin/subjects/${id}/reject`),
        },
        studyPlans: {
            list: apiUrl('/superadmin/study-plans'),
            byId: (id: string | number) => apiUrl(`/superadmin/study-plans/${id}`),
            create: apiUrl('/superadmin/study-plans'),
            update: (id: string | number) => apiUrl(`/superadmin/study-plans/${id}`),
            delete: (id: string | number) => apiUrl(`/superadmin/study-plans/${id}`),
            approve: (id: string | number) => apiUrl(`/superadmin/study-plans/${id}/approve`),
            reject: (id: string | number) => apiUrl(`/superadmin/study-plans/${id}/reject`),
        },
        curriculum: {
            list: (id: string | number) => apiUrl(`/superadmin/study-plans/${id}/curriculum`),
            byId: (studyPlanId: string | number, curriculumId: string | number) => apiUrl(`/superadmin/study-plans/${studyPlanId}/curriculum/${curriculumId}`),
            create: (id: string | number) => apiUrl(`/superadmin/study-plans/${id}/curriculum`),
            update: (studyPlanId: string | number, curriculumId: string | number) => apiUrl(`/superadmin/study-plans/${studyPlanId}/curriculum/${curriculumId}`),
            delete: (studyPlanId: string | number, curriculumId: string | number) => apiUrl(`/superadmin/study-plans/${studyPlanId}/curriculum/${curriculumId}`),
        },
        specialties: {
            list: apiUrl('/superadmin/specialties'),
            byId: (id: string | number) => apiUrl(`/superadmin/specialties/${id}`),
            create: apiUrl('/superadmin/specialties'),
            update: (id: string | number) => apiUrl(`/superadmin/specialties/${id}`),
            delete: (id: string | number) => apiUrl(`/superadmin/specialties/${id}`),
            linked: (id: string | number, subjectId: string | number) => apiUrl(`/superadmin/specialties/${id}/linked/${subjectId}`),
            unlinked: (id: string | number, subjectId: string | number) => apiUrl(`/superadmin/specialties/${id}/unlinked/${subjectId}`),
            listSubjescts: (id: string | number) => apiUrl(`/superadmin/specialties/${id}/subjects`),
            listNotInSubjects: (id: string | number) => apiUrl(`/superadmin/specialties/${id}/not-in/subjects`),
        },
        academicPeriods: {
            list: apiUrl('/superadmin/academic-periods'),
            byId: (id: string | number) => apiUrl(`/superadmin/academic-periods/${id}`),
            create: apiUrl('/superadmin/academic-periods'),
            update: (id: string | number) => apiUrl(`/superadmin/academic-periods/${id}`),
            delete: (id: string | number) => apiUrl(`/superadmin/academic-periods/${id}`),
        },
        optionalGroups: {
            list: apiUrl('/superadmin/optional-groups'),
            byId: (id: string | number) => apiUrl(`/superadmin/optional-groups/${id}`),
            create: apiUrl('/superadmin/optional-groups'),
            update: (id: string | number) => apiUrl(`/superadmin/optional-groups/${id}`),
            delete: (id: string | number) => apiUrl(`/superadmin/optional-groups/${id}`),
            linked: (id: string | number, subjectId: string | number) => apiUrl(`/superadmin/optional-groups/${id}/linked/${subjectId}`),
            unlinked: (id: string | number, subjectId: string | number) => apiUrl(`/superadmin/optional-groups/${id}/unlinked/${subjectId}`),
            listSubjescts: (id: string | number) => apiUrl(`/superadmin/optional-groups/${id}/subjects`),
            listNotInSubjects: (id: string | number) => apiUrl(`/superadmin/optional-groups/${id}/not-in/subjects`),
        },
        admCatalogs: {
            scholarships: {
                paginate: apiUrl('/superadmin/adm-catalogs/scholarships'),
                byId:     (id: string | number) => apiUrl(`/superadmin/adm-catalogs/scholarships/${id}`),
                create:   apiUrl('/superadmin/adm-catalogs/scholarships'),
                update:   (id: string | number) => apiUrl(`/superadmin/adm-catalogs/scholarships/${id}`),
                delete:   (id: string | number) => apiUrl(`/superadmin/adm-catalogs/scholarships/${id}`),
            },
            academicAreas: {
                paginate: apiUrl('/superadmin/adm-catalogs/academic-areas'),
                byId:     (id: string | number) => apiUrl(`/superadmin/adm-catalogs/academic-areas/${id}`),
                create:   apiUrl('/superadmin/adm-catalogs/academic-areas'),
                update:   (id: string | number) => apiUrl(`/superadmin/adm-catalogs/academic-areas/${id}`),
                delete:   (id: string | number) => apiUrl(`/superadmin/adm-catalogs/academic-areas/${id}`),
            },
            disabilities: {
                paginate: apiUrl('/superadmin/adm-catalogs/disabilities'),
                byId:     (id: string | number) => apiUrl(`/superadmin/adm-catalogs/disabilities/${id}`),
                create:   apiUrl('/superadmin/adm-catalogs/disabilities'),
                update:   (id: string | number) => apiUrl(`/superadmin/adm-catalogs/disabilities/${id}`),
                delete:   (id: string | number) => apiUrl(`/superadmin/adm-catalogs/disabilities/${id}`),
            },
            indigenousGroups: {
                paginate: apiUrl('/superadmin/adm-catalogs/indigenous-groups'),
                byId:     (id: string | number) => apiUrl(`/superadmin/adm-catalogs/indigenous-groups/${id}`),
                create:   apiUrl('/superadmin/adm-catalogs/indigenous-groups'),
                update:   (id: string | number) => apiUrl(`/superadmin/adm-catalogs/indigenous-groups/${id}`),
                delete:   (id: string | number) => apiUrl(`/superadmin/adm-catalogs/indigenous-groups/${id}`),
            },
            indigenousLanguages: {
                paginate: apiUrl('/superadmin/adm-catalogs/indigenous-languages'),
                byId:     (id: string | number) => apiUrl(`/superadmin/adm-catalogs/indigenous-languages/${id}`),
                create:   apiUrl('/superadmin/adm-catalogs/indigenous-languages'),
                update:   (id: string | number) => apiUrl(`/superadmin/adm-catalogs/indigenous-languages/${id}`),
                delete:   (id: string | number) => apiUrl(`/superadmin/adm-catalogs/indigenous-languages/${id}`),
            },
        },
    },
} satisfies ApiModule
