export default [
    {
        path: 'midocencia/rubric',
        name: 'midocencia.rubric',
        component: () => import('@/modules/midocencia/pages/RubricPage.vue'),
        meta: { title: 'Rúbrica de Función Académica' },
    },
    {
        path: 'midocencia/rubric/:id/edit',
        name: 'midocencia.rubric.edit',
        component: () => import('@/modules/midocencia/pages/RubricEditPage.vue'),
        meta: { title: 'Editar Rúbrica' },
    },
    {
        path: 'midocencia/my-distribution',
        name: 'midocencia.my-distribution',
        component: () => import('@/modules/midocencia/pages/MyDistributionPage.vue'),
        meta: { title: 'Mi Docencia' },
    },
    {
        path: 'midocencia/my-schedule',
        name: 'midocencia.my-schedule',
        component: () => import('@/modules/midocencia/pages/MyDischargeSchedulePage.vue'),
        meta: { title: 'Horario de Descarga' },
    },
    {
        path: 'midocencia/my-evidences',
        name: 'midocencia.my-evidences',
        component: () => import('@/modules/midocencia/pages/MyEvidencePage.vue'),
        meta: { title: 'Mis Evidencias' },
    },
    {
        path: 'midocencia/descarga-permits',
        name: 'midocencia.descarga-permits',
        component: () => import('@/modules/midocencia/pages/MyDescargaPermitsPage.vue'),
        meta: { title: 'Permiso de Descarga' },
    },
    {
        path: 'midocencia/descarga-permits/inbox',
        name: 'midocencia.descarga-permits.inbox',
        component: () => import('@/modules/midocencia/pages/DescargaPermitInboxPage.vue'),
        meta: { title: 'Permisos de Descarga' },
    },
    {
        path: 'midocencia/sections',
        name: 'midocencia.sections',
        component: () => import('@/modules/midocencia/pages/SectionEvidenceViewerPage.vue'),
        meta: { title: 'Evidencias por Sección' },
    },
    {
        path: 'midocencia/instrumentations',
        name: 'midocencia.instrumentations',
        component: () => import('@/modules/midocencia/pages/SectionInstrumentationsViewerPage.vue'),
        meta: { title: 'Instrumentaciones' },
    },
    {
        path: 'midocencia/my-otros',
        name: 'midocencia.my-otros',
        component: () => import('@/modules/midocencia/pages/MyOtrosPage.vue'),
        meta: { title: 'Otros (evidencias libres)' },
    },
    {
        path: 'midocencia/otros/buckets',
        name: 'midocencia.otros-buckets',
        component: () => import('@/modules/midocencia/pages/OtrosBucketsAdminPage.vue'),
        meta: { title: 'Categorías de Otros' },
    },
    {
        path: 'midocencia/basicas',
        name: 'midocencia.basicas',
        component: () => import('@/modules/midocencia/pages/BasicasRosterPage.vue'),
        meta: { title: 'Padrón de Ciencias Básicas' },
    },
    {
        path: 'midocencia/basicas/approval',
        name: 'midocencia.basicas.approval',
        component: () => import('@/modules/midocencia/pages/BasicasApprovalPage.vue'),
        meta: { title: 'Ciencias Básicas — Aprobar Horario' },
    },
    {
        path: 'midocencia/approval',
        name: 'midocencia.approval',
        component: () => import('@/modules/midocencia/pages/DistributionApprovalPage.vue'),
        meta: { title: 'Seguimiento de descargas' },
    },
    {
        path: 'midocencia/approval/:id/schedule',
        name: 'midocencia.approval-schedule',
        component: () => import('@/modules/midocencia/pages/ScheduleReviewPage.vue'),
        meta: { title: 'Revisión del horario de descarga' },
    },
    {
        path: 'midocencia/plaza',
        name: 'midocencia.plaza',
        component: () => import('@/modules/midocencia/pages/PlazaPage.vue'),
        meta: { title: 'Horas de Plaza' },
    },
    {
        path: 'midocencia/descarga-types',
        name: 'midocencia.descarga-types',
        component: () => import('@/modules/midocencia/pages/DescargaTypesPage.vue'),
        meta: { title: 'Tipos de Descarga' },
    },
    {
        path: 'midocencia/oficios',
        name: 'midocencia.oficios',
        component: () => import('@/modules/midocencia/pages/OficiosEmitidosPage.vue'),
        meta: { title: 'Oficios Emitidos' },
    },
]
