import { apiUrl } from '@/shared/api/config'
import type { ApiModule } from '@/shared/api/types'

export default {
    name: 'ADMISSIONS_API',
    api: {
        originSchools: {
            list:   apiUrl('/admissions/origin-schools'),
            byId:   (id: string | number) => apiUrl(`/admissions/origin-schools/${id}`),
            create: apiUrl('/admissions/origin-schools'),
            update: (id: string | number) => apiUrl(`/admissions/origin-schools/${id}`),
            delete: (id: string | number) => apiUrl(`/admissions/origin-schools/${id}`),
        },
        documentTypes: {
            list:   apiUrl('/admissions/document-types'),
            byId:   (id: string | number) => apiUrl(`/admissions/document-types/${id}`),
            create: apiUrl('/admissions/document-types'),
            update: (id: string | number) => apiUrl(`/admissions/document-types/${id}`),
            delete: (id: string | number) => apiUrl(`/admissions/document-types/${id}`),
        },
        globalRequiredDocuments: {
            list:   apiUrl('/admissions/global-required-documents'),
            byId:   (id: string | number) => apiUrl(`/admissions/global-required-documents/${id}`),
            create: apiUrl('/admissions/global-required-documents'),
            update: (id: string | number) => apiUrl(`/admissions/global-required-documents/${id}`),
            delete: (id: string | number) => apiUrl(`/admissions/global-required-documents/${id}`),
        },
        offerRequiredDocuments: {
            list:   (offerId: string | number) => apiUrl(`/admissions/academic-offers/${offerId}/required-documents`),
            byId:   (offerId: string | number, id: string | number) => apiUrl(`/admissions/academic-offers/${offerId}/required-documents/${id}`),
            create: (offerId: string | number) => apiUrl(`/admissions/academic-offers/${offerId}/required-documents`),
            update: (offerId: string | number, id: string | number) => apiUrl(`/admissions/academic-offers/${offerId}/required-documents/${id}`),
            delete: (offerId: string | number, id: string | number) => apiUrl(`/admissions/academic-offers/${offerId}/required-documents/${id}`),
        },
        applicants: {
            list:          apiUrl('/admissions/applicants'),
            byId:          (id: string | number) => apiUrl(`/admissions/applicants/${id}`),
            create:        apiUrl('/admissions/applicants'),
            update:        (id: string | number) => apiUrl(`/admissions/applicants/${id}`),
            delete:        (id: string | number) => apiUrl(`/admissions/applicants/${id}`),
            photo:         (id: string | number) => apiUrl(`/admissions/applicants/${id}/photo`),
            avatar:        (id: string | number, size: 'sm' | 'md' | 'lg' = 'md') => apiUrl(`/admissions/applicants/${id}/avatar?size=${size}`),
            resetPassword: (id: string | number) => apiUrl(`/admissions/applicants/${id}/reset-password`),
        },
        config: {
            get:    apiUrl('/admissions/config'),
            update: apiUrl('/admissions/config'),
        },
        applicantStatuses: {
            list:   apiUrl('/admissions/applicant-statuses'),
            byId:   (id: string | number) => apiUrl(`/admissions/applicant-statuses/${id}`),
            update: (id: string | number) => apiUrl(`/admissions/applicant-statuses/${id}`),
        },
        enrollmentWindows: {
            list:   apiUrl('/admissions/enrollment-windows'),
            active: apiUrl('/admissions/enrollment-windows/active'),
            byId:   (id: string | number) => apiUrl(`/admissions/enrollment-windows/${id}`),
            create: apiUrl('/admissions/enrollment-windows'),
            update: (id: string | number) => apiUrl(`/admissions/enrollment-windows/${id}`),
            delete: (id: string | number) => apiUrl(`/admissions/enrollment-windows/${id}`),
        },
        portal: {
            me:          apiUrl('/admissions/portal/me'),
            documents:   apiUrl('/admissions/portal/documents'),
            upload:      apiUrl('/admissions/portal/documents/upload'),
            download:    (documentId: string | number) => apiUrl(`/admissions/portal/documents/${documentId}/download`),
            verifyEmail: (id: string | number, hash: string) => apiUrl(`/admissions/verify-email?id=${id}&hash=${encodeURIComponent(hash)}`),
        },
        applicantDocuments: {
            list:     (applicantId: string | number) => apiUrl(`/admissions/applicants/${applicantId}/documents`),
            byId:     (applicantId: string | number, id: string | number) => apiUrl(`/admissions/applicants/${applicantId}/documents/${id}`),
            create:   (applicantId: string | number) => apiUrl(`/admissions/applicants/${applicantId}/documents`),
            update:   (applicantId: string | number, id: string | number) => apiUrl(`/admissions/applicants/${applicantId}/documents/${id}`),
            delete:   (applicantId: string | number, id: string | number) => apiUrl(`/admissions/applicants/${applicantId}/documents/${id}`),
            upload:   (applicantId: string | number) => apiUrl(`/admissions/applicants/${applicantId}/documents/upload`),
            download: (applicantId: string | number, documentId: string | number) => apiUrl(`/admissions/applicants/${applicantId}/documents/${documentId}/download`),
            review:   (applicantId: string | number, id: string | number) => apiUrl(`/admissions/applicants/${applicantId}/documents/${id}/review`),
        },
        scholarships: {
            list:     () => apiUrl('/admissions/scholarships/list'),
            paginate: apiUrl('/admissions/scholarships'),
            byId:     (id: string | number) => apiUrl(`/admissions/scholarships/${id}`),
            create:   apiUrl('/admissions/scholarships'),
            update:   (id: string | number) => apiUrl(`/admissions/scholarships/${id}`),
            delete:   (id: string | number) => apiUrl(`/admissions/scholarships/${id}`),
        },
        academicAreas: {
            list:     () => apiUrl('/admissions/academic-areas/list'),
            paginate: apiUrl('/admissions/academic-areas'),
            byId:     (id: string | number) => apiUrl(`/admissions/academic-areas/${id}`),
            create:   apiUrl('/admissions/academic-areas'),
            update:   (id: string | number) => apiUrl(`/admissions/academic-areas/${id}`),
            delete:   (id: string | number) => apiUrl(`/admissions/academic-areas/${id}`),
        },
        disabilities: {
            list:     () => apiUrl('/admissions/disabilities/list'),
            paginate: apiUrl('/admissions/disabilities'),
            byId:     (id: string | number) => apiUrl(`/admissions/disabilities/${id}`),
            create:   apiUrl('/admissions/disabilities'),
            update:   (id: string | number) => apiUrl(`/admissions/disabilities/${id}`),
            delete:   (id: string | number) => apiUrl(`/admissions/disabilities/${id}`),
        },
        indigenousGroups: {
            list:     () => apiUrl('/admissions/indigenous-groups/list'),
            paginate: apiUrl('/admissions/indigenous-groups'),
            byId:     (id: string | number) => apiUrl(`/admissions/indigenous-groups/${id}`),
            create:   apiUrl('/admissions/indigenous-groups'),
            update:   (id: string | number) => apiUrl(`/admissions/indigenous-groups/${id}`),
            delete:   (id: string | number) => apiUrl(`/admissions/indigenous-groups/${id}`),
        },
        indigenousLanguages: {
            list:     () => apiUrl('/admissions/indigenous-languages/list'),
            paginate: apiUrl('/admissions/indigenous-languages'),
            byId:     (id: string | number) => apiUrl(`/admissions/indigenous-languages/${id}`),
            create:   apiUrl('/admissions/indigenous-languages'),
            update:   (id: string | number) => apiUrl(`/admissions/indigenous-languages/${id}`),
            delete:   (id: string | number) => apiUrl(`/admissions/indigenous-languages/${id}`),
        },
        applicantContacts: {
            list:   (applicantId: string | number) => apiUrl(`/admissions/applicants/${applicantId}/contacts`),
            byId:   (applicantId: string | number, id: string | number) => apiUrl(`/admissions/applicants/${applicantId}/contacts/${id}`),
            create: (applicantId: string | number) => apiUrl(`/admissions/applicants/${applicantId}/contacts`),
            update: (applicantId: string | number, id: string | number) => apiUrl(`/admissions/applicants/${applicantId}/contacts/${id}`),
            delete: (applicantId: string | number, id: string | number) => apiUrl(`/admissions/applicants/${applicantId}/contacts/${id}`),
        },
    },
} satisfies ApiModule
