import { apiUrl } from '@/shared/api/config'
import type { ApiModule } from '@/shared/api/types'

export default {
    name: 'ADMISSIONS_API',
    api: {
        originSchools: {
            list:   apiUrl('/admissions/origin-schools'),
            byId:   (id: string | number) => apiUrl(`/admissions/origin-schools/${id}`),
            create: apiUrl('/admissions/origin-schools'),
            update: (id: string | number) => apiUrl(`/admissions/origin-schools/${id}`),
            delete: (id: string | number) => apiUrl(`/admissions/origin-schools/${id}`),
        },
        documentTypes: {
            list:   apiUrl('/admissions/document-types'),
            byId:   (id: string | number) => apiUrl(`/admissions/document-types/${id}`),
            create: apiUrl('/admissions/document-types'),
            update: (id: string | number) => apiUrl(`/admissions/document-types/${id}`),
            delete: (id: string | number) => apiUrl(`/admissions/document-types/${id}`),
        },
        globalRequiredDocuments: {
            list:   apiUrl('/admissions/global-required-documents'),
            byId:   (id: string | number) => apiUrl(`/admissions/global-required-documents/${id}`),
            create: apiUrl('/admissions/global-required-documents'),
            update: (id: string | number) => apiUrl(`/admissions/global-required-documents/${id}`),
            delete: (id: string | number) => apiUrl(`/admissions/global-required-documents/${id}`),
        },
        offerRequiredDocuments: {
            list:   (offerId: string | number) => apiUrl(`/admissions/academic-offers/${offerId}/required-documents`),
            byId:   (offerId: string | number, id: string | number) => apiUrl(`/admissions/academic-offers/${offerId}/required-documents/${id}`),
            create: (offerId: string | number) => apiUrl(`/admissions/academic-offers/${offerId}/required-documents`),
            update: (offerId: string | number, id: string | number) => apiUrl(`/admissions/academic-offers/${offerId}/required-documents/${id}`),
            delete: (offerId: string | number, id: string | number) => apiUrl(`/admissions/academic-offers/${offerId}/required-documents/${id}`),
            counts: apiUrl('/admissions/offer-required-documents/counts'),
        },
        applicants: {
            list:          apiUrl('/admissions/applicants'),
            docsToReviewCount: apiUrl('/admissions/applicants/docs-to-review-count'),
            documentsSummary:  apiUrl('/admissions/applicants/documents-summary'),
            byId:          (id: string | number) => apiUrl(`/admissions/applicants/${id}`),
            create:        apiUrl('/admissions/applicants'),
            update:        (id: string | number) => apiUrl(`/admissions/applicants/${id}`),
            delete:        (id: string | number) => apiUrl(`/admissions/applicants/${id}`),
            photo:         (id: string | number) => apiUrl(`/admissions/applicants/${id}/photo`),
            avatar:        (id: string | number, size: 'sm' | 'md' | 'lg' = 'md') => apiUrl(`/admissions/applicants/${id}/avatar?size=${size}`),
            resetPassword: (id: string | number) => apiUrl(`/admissions/applicants/${id}/reset-password`),
            neighbors:     (id: string | number) => apiUrl(`/admissions/applicants/${id}/neighbors`),
            releaseResult: (id: string | number) => apiUrl(`/admissions/applicants/${id}/release-result`),
            bulkRelease:   apiUrl('/admissions/applicants/release-results-bulk'),
            scoresOverview: apiUrl('/admissions/applicants/scores-overview'),
            setScore:      (id: string | number) => apiUrl(`/admissions/applicants/${id}/score`),
            myExamResult:  apiUrl('/admissions/applicants/me/exam-result'),
        },
        admissionProcess: {
            close: apiUrl('/admissions/process/close'),
        },
        proctorRecords: {
            pending:  apiUrl('/admissions/proctor-records/pending'),
            validate: (id: string | number) => apiUrl(`/admissions/proctor-records/${id}/validate`),
            mine:     apiUrl('/admissions/proctor-records/mine'),
        },
        config: {
            get:    apiUrl('/admissions/config'),
            update: apiUrl('/admissions/config'),
            list:   apiUrl('/admissions/config/list'),
            byId:   (id: string | number) => apiUrl(`/admissions/config/${id}`),
        },
        examModeOverrides: {
            list:   apiUrl('/admissions/exam-mode-overrides'),
            update: (modalityId: number) => apiUrl(`/admissions/exam-mode-overrides/${modalityId}`),
        },
        applicantStatuses: {
            list:   apiUrl('/admissions/applicant-statuses'),
            byId:   (id: string | number) => apiUrl(`/admissions/applicant-statuses/${id}`),
            update: (id: string | number) => apiUrl(`/admissions/applicant-statuses/${id}`),
        },
        enrollmentWindows: {
            list:   apiUrl('/admissions/enrollment-windows'),
            active: apiUrl('/admissions/enrollment-windows/active'),
            byId:   (id: string | number) => apiUrl(`/admissions/enrollment-windows/${id}`),
            create: apiUrl('/admissions/enrollment-windows'),
            update: (id: string | number) => apiUrl(`/admissions/enrollment-windows/${id}`),
            delete: (id: string | number) => apiUrl(`/admissions/enrollment-windows/${id}`),
        },
        portal: {
            me:                 apiUrl('/admissions/portal/me'),
            update:             apiUrl('/admissions/portal/me'),
            password:           apiUrl('/admissions/portal/password'),
            photo:              apiUrl('/admissions/portal/photo'),
            avatar:             apiUrl('/admissions/portal/avatar'),
            documents:          apiUrl('/admissions/portal/documents'),
            upload:             apiUrl('/admissions/portal/documents/upload'),
            download:           (documentId: string | number) => apiUrl(`/admissions/portal/documents/${documentId}/download`),
            emailStatus:        apiUrl('/admissions/portal/email-status'),
            resendVerification: apiUrl('/admissions/portal/resend-verification'),
            verifyEmail:        (id: string | number, hash: string) => apiUrl(`/admissions/verify-email?id=${id}&hash=${encodeURIComponent(hash)}`),
            contacts: {
                list:   apiUrl('/admissions/portal/contacts'),
                create: apiUrl('/admissions/portal/contacts'),
                update: (id: string | number) => apiUrl(`/admissions/portal/contacts/${id}`),
                delete: (id: string | number) => apiUrl(`/admissions/portal/contacts/${id}`),
            },
            prefichaConfig: apiUrl('/admissions/portal/preficha-config'),
            obtainPreFicha: apiUrl('/admissions/portal/obtain-preficha'),
            catalogs: {
                disabilities:        apiUrl('/admissions/portal/catalogs/disabilities'),
                indigenousGroups:    apiUrl('/admissions/portal/catalogs/indigenous-groups'),
                indigenousLanguages: apiUrl('/admissions/portal/catalogs/indigenous-languages'),
                academicAreas:       apiUrl('/admissions/portal/catalogs/academic-areas'),
                scholarships:        apiUrl('/admissions/portal/catalogs/scholarships'),
                academicOffers:      apiUrl('/admissions/portal/catalogs/academic-offers'),
                originSchools:       apiUrl('/admissions/portal/catalogs/origin-schools'),
                originSchoolById:    (id: string | number) => apiUrl(`/admissions/portal/catalogs/origin-schools/${id}`),
                originSchoolStates:  apiUrl('/admissions/portal/catalogs/origin-school-states'),
                originSchoolMunicipalities: (stateId: string | number) => apiUrl(`/admissions/portal/catalogs/origin-school-municipalities/${stateId}`),
            },
        },
        applicantDocuments: {
            list:     (applicantId: string | number) => apiUrl(`/admissions/applicants/${applicantId}/documents`),
            byId:     (applicantId: string | number, id: string | number) => apiUrl(`/admissions/applicants/${applicantId}/documents/${id}`),
            create:   (applicantId: string | number) => apiUrl(`/admissions/applicants/${applicantId}/documents`),
            update:   (applicantId: string | number, id: string | number) => apiUrl(`/admissions/applicants/${applicantId}/documents/${id}`),
            delete:   (applicantId: string | number, id: string | number) => apiUrl(`/admissions/applicants/${applicantId}/documents/${id}`),
            upload:   (applicantId: string | number) => apiUrl(`/admissions/applicants/${applicantId}/documents/upload`),
            download: (applicantId: string | number, documentId: string | number) => apiUrl(`/admissions/applicants/${applicantId}/documents/${documentId}/download`),
            review:   (applicantId: string | number, id: string | number) => apiUrl(`/admissions/applicants/${applicantId}/documents/${id}/review`),
        },
        scholarships: {
            list:     () => apiUrl('/admissions/scholarships/list'),
            paginate: apiUrl('/admissions/scholarships'),
            byId:     (id: string | number) => apiUrl(`/admissions/scholarships/${id}`),
            create:   apiUrl('/admissions/scholarships'),
            update:   (id: string | number) => apiUrl(`/admissions/scholarships/${id}`),
            delete:   (id: string | number) => apiUrl(`/admissions/scholarships/${id}`),
        },
        academicAreas: {
            list:     () => apiUrl('/admissions/academic-areas/list'),
            paginate: apiUrl('/admissions/academic-areas'),
            byId:     (id: string | number) => apiUrl(`/admissions/academic-areas/${id}`),
            create:   apiUrl('/admissions/academic-areas'),
            update:   (id: string | number) => apiUrl(`/admissions/academic-areas/${id}`),
            delete:   (id: string | number) => apiUrl(`/admissions/academic-areas/${id}`),
        },
        disabilities: {
            list:     () => apiUrl('/admissions/disabilities/list'),
            paginate: apiUrl('/admissions/disabilities'),
            byId:     (id: string | number) => apiUrl(`/admissions/disabilities/${id}`),
            create:   apiUrl('/admissions/disabilities'),
            update:   (id: string | number) => apiUrl(`/admissions/disabilities/${id}`),
            delete:   (id: string | number) => apiUrl(`/admissions/disabilities/${id}`),
        },
        indigenousGroups: {
            list:     () => apiUrl('/admissions/indigenous-groups/list'),
            paginate: apiUrl('/admissions/indigenous-groups'),
            byId:     (id: string | number) => apiUrl(`/admissions/indigenous-groups/${id}`),
            create:   apiUrl('/admissions/indigenous-groups'),
            update:   (id: string | number) => apiUrl(`/admissions/indigenous-groups/${id}`),
            delete:   (id: string | number) => apiUrl(`/admissions/indigenous-groups/${id}`),
        },
        indigenousLanguages: {
            list:     () => apiUrl('/admissions/indigenous-languages/list'),
            paginate: apiUrl('/admissions/indigenous-languages'),
            byId:     (id: string | number) => apiUrl(`/admissions/indigenous-languages/${id}`),
            create:   apiUrl('/admissions/indigenous-languages'),
            update:   (id: string | number) => apiUrl(`/admissions/indigenous-languages/${id}`),
            delete:   (id: string | number) => apiUrl(`/admissions/indigenous-languages/${id}`),
        },
        applicantContacts: {
            list:   (applicantId: string | number) => apiUrl(`/admissions/applicants/${applicantId}/contacts`),
            byId:   (applicantId: string | number, id: string | number) => apiUrl(`/admissions/applicants/${applicantId}/contacts/${id}`),
            create: (applicantId: string | number) => apiUrl(`/admissions/applicants/${applicantId}/contacts`),
            update: (applicantId: string | number, id: string | number) => apiUrl(`/admissions/applicants/${applicantId}/contacts/${id}`),
            delete: (applicantId: string | number, id: string | number) => apiUrl(`/admissions/applicants/${applicantId}/contacts/${id}`),
        },
        applicantScores: {
            json: apiUrl('/admissions/applicants/scores'),
            csv:  apiUrl('/admissions/applicants/scores/csv'),
        },
        examOnlineSync: {
            status: apiUrl('/admissions/exam-online/sync-status'),
            run:    apiUrl('/admissions/exam-online/sync'),
        },
        applicantRanking: {
            list:              (params: string) => apiUrl(`/admissions/applicants/ranking?${params}`),
            pendingEvaluation: (params: string) => apiUrl(`/admissions/applicants/pending-evaluation?${params}`),
            admitBulk:         apiUrl('/admissions/applicants/admit-bulk'),
        },
        statistics: {
            context:            apiUrl('/admissions/statistics/context'),
            funnel:             (params: string) => apiUrl(`/admissions/statistics/funnel?${params}`),
            scoreDistribution:  (params: string) => apiUrl(`/admissions/statistics/score-distribution?${params}`),
            offerDemand:        (params: string) => apiUrl(`/admissions/statistics/offer-demand?${params}`),
            examAttendance:     (params: string) => apiUrl(`/admissions/statistics/exam-attendance?${params}`),
            ageAndMode:         (params: string) => apiUrl(`/admissions/statistics/age-and-mode?${params}`),
            originDistribution: (params: string) => apiUrl(`/admissions/statistics/origin-distribution?${params}`),
            inclusion:          (params: string) => apiUrl(`/admissions/statistics/inclusion?${params}`),
        },
        reports: {
            fichas: (params: string = '') =>
                apiUrl(`/admissions/reports/fichas${params ? '?' + params : ''}`),
            nonAdmission: (params: string = '') =>
                apiUrl(`/admissions/reports/non-admission${params ? '?' + params : ''}`),
        },
        registration: {
            register:     apiUrl('/admissions/register'),
            activeWindow: (collegeId: string | number) => apiUrl(`/admissions/active-window?college_id=${collegeId}`),
        },
        examProctorCandidates: apiUrl('/admissions/exam-proctor-candidates'),
        examSessions: {
            list:             apiUrl('/admissions/exam-sessions'),
            byId:             (id: string | number) => apiUrl(`/admissions/exam-sessions/${id}`),
            create:           apiUrl('/admissions/exam-sessions'),
            update:           (id: string | number) => apiUrl(`/admissions/exam-sessions/${id}`),
            delete:           (id: string | number) => apiUrl(`/admissions/exam-sessions/${id}`),
            reschedule:       (id: string | number) => apiUrl(`/admissions/exam-sessions/${id}/reschedule`),
            cancel:           (id: string | number) => apiUrl(`/admissions/exam-sessions/${id}/cancel`),
            previewConflicts: apiUrl('/admissions/exam-sessions/preview-conflicts'),

            proctors: {
                list:   (sessionId: string | number) => apiUrl(`/admissions/exam-sessions/${sessionId}/proctors`),
                create: (sessionId: string | number) => apiUrl(`/admissions/exam-sessions/${sessionId}/proctors`),
                delete: (sessionId: string | number, id: string | number) => apiUrl(`/admissions/exam-sessions/${sessionId}/proctors/${id}`),
            },

            assignments: {
                list:   (sessionId: string | number) => apiUrl(`/admissions/exam-sessions/${sessionId}/assignments`),
                create: (sessionId: string | number) => apiUrl(`/admissions/exam-sessions/${sessionId}/assignments`),
                delete: (sessionId: string | number, id: string | number) => apiUrl(`/admissions/exam-sessions/${sessionId}/assignments/${id}`),
            },

            warnings: (sessionId: string | number) => apiUrl(`/admissions/exam-sessions/${sessionId}/warnings`),
            regenerateWarnings: (sessionId: string | number) => apiUrl(`/admissions/exam-sessions/${sessionId}/regenerate-warnings`),
        },
        examAssignments: {
            autoDistribute: apiUrl('/admissions/exam-assignments/auto-distribute'),
            bulkReassign:   apiUrl('/admissions/exam-assignments/bulk-reassign'),
        },
        examWarnings: {
            myCareers:   apiUrl('/admissions/exam-warnings/my-careers'),
            acknowledge: (id: string | number) => apiUrl(`/admissions/exam-warnings/${id}/acknowledge`),
        },
        portalExamPass:      apiUrl('/admissions/portal/exam-pass'),
        portalExamPassToken: apiUrl('/admissions/portal/exam-pass/token'),
        examAttendance: {
            mySessions: apiUrl('/admissions/exam-attendance/my-sessions'),
            start:      (sessionId: string | number) => apiUrl(`/admissions/exam-attendance/sessions/${sessionId}/start`),
            close:      (sessionId: string | number) => apiUrl(`/admissions/exam-attendance/sessions/${sessionId}/close`),
            pause:      (sessionId: string | number) => apiUrl(`/admissions/exam-attendance/sessions/${sessionId}/pause`),
            resume:     (sessionId: string | number) => apiUrl(`/admissions/exam-attendance/sessions/${sessionId}/resume`),
            suspend:    (sessionId: string | number) => apiUrl(`/admissions/exam-attendance/sessions/${sessionId}/suspend`),
            checkIn:    (sessionId: string | number) => apiUrl(`/admissions/exam-attendance/sessions/${sessionId}/check-in`),
            mark:       (assignmentId: string | number) => apiUrl(`/admissions/exam-attendance/assignments/${assignmentId}/status`),
        },
    },
} satisfies ApiModule
